# Generated by Django 4.2.4 on 2024-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='categoria',
            field=models.CharField(default='Sin categoria', max_length=100),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
